name: Build & Deploy Template

on:
  workflow_call:
    inputs:
      enivronment:
        required: true
        type: string
        description: The environment to deploy to.
      deploy_repo:
        required: true
        type: string
        description: The name of the repository associated with the environment to deploy to.

env:
  URL: ${{ github.repository_owner }}.github.io/${{ inputs.deploy_repo }}
  ARTIFACT_NAME: build

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Working Repo (${{ github.repository }})
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build:deploy

      - name: Upload Artifact (${{ env.ARTIFACT_NAME }})
        uses: actions/upload-artifact@v4
        with:
          path: dist
          name: ${{ env.ARTIFACT_NAME }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.enivronment }}
      url: https://${{ env.URL }}
    permissions:
      contents: write
    steps:
      - name: Checkout Deployment Repo (${{ inputs.deploy_repo }})
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/${{ inputs.deploy_repo }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: deploy

      - name: Download Artifact (${{ env.ARTIFACT_NAME }})
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: dist

      - name: Copy Files
        run: cp -r dist/* deploy

      - name: Disable Jekyll
        run: touch deploy/.nojekyll

      - name: Configure CNAME
        run: echo ${{ env.URL }} > deploy/CNAME

      - name: Set GitHub Actions as Commit Author
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
      
      - name: Commit & Push
        run: |
          git add .
          git commit -m $GITHUB_SHA
          git push
        working-directory: deploy
