name: Development Build & Deploy
on: 
  push:
    branches:
      - dev
    paths-ignore:
      - .github/workflows/**
      - '**.md'
      - .vscode/**
      - .gitignore

  workflow_dispatch:

jobs:
  call-deploy-template:
    uses: ./.github/workflows/templates/deploy-template.yml
    with:
      enivronment: development
      deploy_repo: portfolio-dev
